### ISSUE TITLE
Deploy to testnets

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#101]
Deploy following contracts:
- [x] Allo core
- [x] Registry
- [x] Donation voting

Deploy to following chains:
- [x] Optimism Goerli
- [x] PGN Testnet
- [x] Sepolia
- [x] Goerli

**Comment by codenamejason** [comment]
So far deployed to `sepolia`

Still need to run `op-goerli` - same as `pgn-testnet`

**Comment by KurtMerbeth** [comment]
# Contract Deployment Information

## Core Contracts

| Contract                       | Address                                      | Goerli | Optimism Goerli | Sepolia | PGN Sepolia |
|--------------------------------|----------------------------------------------|:------:|:---------------:|:-------:|:-----------:|
| Registry | `0xe571ec2C7b94dE72Bc01937a251E48780DEF882A` | [🔗](https://goerli.etherscan.io/address/0xe571ec2C7b94dE72Bc01937a251E48780DEF882A) |      [🔗](https://goerli-optimism.etherscan.io/address/0xe571ec2C7b94dE72Bc01937a251E48780DEF882A)     | [🔗](https://sepolia.etherscan.io/address/0xe571ec2C7b94dE72Bc01937a251E48780DEF882A)  |   [🔗](https://explorer.sepolia.publicgoods.network/address/0xe571ec2C7b94dE72Bc01937a251E48780DEF882A)    |
| Allo | `0x45F5506b0014cbdc9652854B65eed90E56aB7dA9` | [🔗](https://goerli.etherscan.io/address/0x45F5506b0014cbdc9652854B65eed90E56aB7dA9) |      [🔗](https://goerli-optimism.etherscan.io/address/0x45F5506b0014cbdc9652854B65eed90E56aB7dA9)     | [🔗](https://sepolia.etherscan.io/address/0x45F5506b0014cbdc9652854B65eed90E56aB7dA9)  |   [🔗](https://explorer.sepolia.publicgoods.network/address/0x45F5506b0014cbdc9652854B65eed90E56aB7dA9)    |
| Allo Proxy | `0x97122901b6346a625294d446f5d0b7bc00a3b0f2` | [🔗](https://goerli.etherscan.io/address/0x97122901b6346a625294d446f5d0b7bc00a3b0f2) |      [🔗](https://goerli-optimism.etherscan.io/address/0x97122901b6346a625294d446f5d0b7bc00a3b0f2)     | [🔗](https://sepolia.etherscan.io/address/0x97122901b6346a625294d446f5d0b7bc00a3b0f2)  |   [🔗](https://explorer.sepolia.publicgoods.network/address/0x97122901b6346a625294d446f5d0b7bc00a3b0f2)    |

## Strategies

| Contract                       | Address                                      | Goerli | Optimism Goerli | Sepolia | PGN Sepolia |
|--------------------------------|----------------------------------------------|:------:|:---------------:|:-------:|:-----------:|
| Donation Voting v1 | `0x4AB4eF1aa0c2f63FFE77b245E679fb7B38681470` | [🔗](https://goerli.etherscan.io/address/0x4AB4eF1aa0c2f63FFE77b245E679fb7B38681470) |      [🔗](https://goerli-optimism.etherscan.io/address/0x4AB4eF1aa0c2f63FFE77b245E679fb7B38681470)     | [🔗](https://sepolia.etherscan.io/address/0x4AB4eF1aa0c2f63FFE77b245E679fb7B38681470)  |   [🔗](https://explorer.sepolia.publicgoods.network/address/0x4AB4eF1aa0c2f63FFE77b245E679fb7B38681470)    |

## Developer Contracts

| Contract                       | Address                                      | Goerli | Optimism Goerli | Sepolia | PGN Sepolia |
|--------------------------------|----------------------------------------------|:------:|:---------------:|:-------:|:-----------:|
| Deployer | `0x339d087B3ab5DF79c6c3617B2487e5340F2DBE3f` | [🔗](https://goerli.etherscan.io/address/0x339d087B3ab5DF79c6c3617B2487e5340F2DBE3f) |      [🔗](https://goerli-optimism.etherscan.io/address/0x339d087B3ab5DF79c6c3617B2487e5340F2DBE3f)     | [🔗](https://sepolia.etherscan.io/address/0x339d087B3ab5DF79c6c3617B2487e5340F2DBE3f)  |   [🔗](https://explorer.sepolia.publicgoods.network/address/0x339d087B3ab5DF79c6c3617B2487e5340F2DBE3f)    |
