### ISSUE TITLE
Incorrect `metadataRequired` initialization in `DirectGrantsSimpleStrategy`

### ISSUE THREAD

**Issue by andreivladbrg** [allo-protocol/allo-v2#128]
https://github.com/allo-protocol/allo-v2/blob/3bc2f0e53444b84d7dd210a5a440e278407729ff/contracts/strategies/direct-grants-simple/DirectGrantsSimpleStrategy.sol#L109

It should have been:

```solidity
metadataRequired = _metadataRequired;
```

**Comment by codenamejason** [comment]
Nice catch 🙌
