### ISSUE TITLE
Strategy Methods

### ISSUE THREAD

**Issue by 0xZakk** [allo-protocol/allo-v2#202]
**Location:** `/docs/strategy-methods.md`

**Description:**
- What are the three strategy methods?
- For each strategy method,
    - How does it work? (Allo, strategy)
    - What can it do?
    - What can it (explicitly) not do?

**Comment by thelostone-mc** [comment]
https://github.com/allo-protocol/allo-v2/blob/readme-dump/contracts/readme/BaseStrategy.md
