### ISSUE TITLE
System Roles and Actors

### ISSUE THREAD

**Issue by 0xZakk** [allo-protocol/allo-v2#205]
**Location:** `/docs/roles-and-actors.md`

**Description:**
- What are all the roles throughout the entire system?
- For each role:
   - What contract(s) is the role in?
   - What can the role do?
   - What can the role not do?

**Comment by thelostone-mc** [comment]
https://github.com/allo-protocol/allo-v2/blob/readme-dump/contracts/readme/Overview.md#roles-and-actors
