### ISSUE TITLE
Contracts

### ISSUE THREAD

**Issue by 0xZakk** [allo-protocol/allo-v2#206]
**Location:** `/docs/contracts.md`

**Description:**
- For every contract in the audit (including the short and small ones)
    - What is the purpose of the contract?
    - What other contracts (internal to Allo) does it interact with?
    - What other contracts (external to Allo) does it interact with?
    - Link to natspec generated doc from #197

**Comment by thelostone-mc** [comment]
https://github.com/allo-protocol/allo-v2/blob/readme-dump/contracts/readme/Overview.md#contract-overview
