### ISSUE TITLE
[Major] Use Initializable

### ISSUE THREAD

**Issue by 0xKurt** [allo-protocol/allo-v2#211]
Check all `initialize` functions and update to use `Initializable`.

Explore if it makes sense to add it only to the `BaseStrategy`

**Comment by thelostone-mc** [comment]
Looks like the core contracts have implemented initialize.
Within strategies, forcing to use initialize make them upgradeble which some clients might not want.
I'd lean towards keeping the decision of whether a strategy should be upgradeable to  the strategy owner

**Comment by thelostone-mc** [comment]
Removed unused library : 38bbd3e
