### ISSUE TITLE
[Medium] Ensure fundPool can only be called before distribution starts

### ISSUE THREAD

**Issue by 0xKurt** [allo-protocol/allo-v2#215]

**Comment by thelostone-mc** [comment]
Is there a downside of allowing this behaviour ? 
This does allow the pool manager to fund it batches ? I don't see why they would do this but i don't think it causes any issues as the excess funds can be withdrawn

**Comment by thelostone-mc** [comment]
Discussed with @0xKurt !
Agreed that this logic is strategy specific and can be implemented via hooks which have been added to BaseStrategy via #254
