### ISSUE TITLE
Fix Allo v2 deploy script

### ISSUE THREAD

**Issue by 0xKurt** [allo-protocol/allo-v2#223]
After deploying the contracts, the Allo contract is not initialized. We need to fix it.

- [x] PGN and Celo verifications need to be checked for all contracts
- [x] PGN and Celo Allo initialization needs to be checked
- [x] PGN and Celo Whitelist of Merkle and Direct strategies needs to be checked
- [x] Deploy script needs to be updated to init the allo contract after deployment
- [x] Add documentation / requirement md file for chain requirements to deploy (EVM, hardhat-upgradeable, gnosis safe, subgraph, permit2, anything else?)

**Comment by nfrgosselin** [comment]
This is finished per standup on 9/6
