### ISSUE TITLE
Spike: Confirm Direct grants Safe functionality

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#228]
**Timebox to one hour**

Many existing direct grants programs use [Safe](https://safe.global/) as a core part of their workflow. While we're still learning about direct grants programs and their use cases, we want to make sure that we're compatible with their needs. 

The [direct grants simple strategy](https://github.com/allo-protocol/allo-v2/tree/main/contracts/strategies/direct-grants-simple) needs to allow:
- the program's Safe(s) to call `fundPool`, so that funds can be transferred from the Safe into the Allo pool
- pool managers to have the option of:
    - funding the pool in lump sum(s) 
    OR
    - funding the pool as needed when funds are allocated to a grantee

**Comment by thelostone-mc** [comment]
- Anyone including a safe can fund the pool
- The flow is as follows:

- Recipient registers to pool
- Recipient can set milestones
- Pool Manager can set milestones on behalf of recipient (auto approve milestones)
- Pool Manager can review set milestones
- Pool Manager can allocate how much funds a recipient should get (THIS STEP REQUIRES FUNDS TO BE IN THE CONTRACT)
- Recipient can submit milestone when completed (only after a recipient is accepted)
- Pool Manager can reject milestone
- Pool Manager can distribute funds for a given milestone (this approves the milestone and pays out)
