### ISSUE TITLE
Era (zkSync) Allo v1 deployment (by 9/18)

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#238]
- [x] v1 core contracts to testnet
- [x] v1 subgraphs to testnet
- [x] v1 core contracts to mainnet
- [x] v1 subgraphs to mainnet

**Comment by codenamejason** [comment]
@thelostone-mc 

@0xKurt and I went over the deploy script today for an hour or so and were able to deploy all contracts but were unable to verify the `ProgramFactory` contract.

**Comment by thelostone-mc** [comment]
Contracts deployed via https://github.com/allo-protocol/allo-contracts/pull/96

**Comment by thelostone-mc** [comment]
All have been deployed
