### ISSUE TITLE
Polygon PoS Allo v1 deployment (by 9/18)

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#239]
- [x] v1 core contracts to testnet
- [x] v1 subgraphs to testnet

- [x] v1 core contracts to mainnet
- [x] v1 subgraphs to mainnet

[Contracts PR Link](https://github.com/allo-protocol/allo-contracts/pull/95)
[Graph PR Link](https://github.com/allo-protocol/graph/pull/26)

**Comment by codenamejason** [comment]
@thelostone-mc @0xKurt  I was again unable to verify the two payout strategies. Not sure what I am doing wrong there. All others are verified on mumbai.
