### ISSUE TITLE
[spike] Check v1/v2 compatibility with Era

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#240]
**timebox to 1 hour**

In light of https://www.npmjs.com/package/@matterlabs/hardhat-zksync-upgradable, confirm whether or not Allo v1/v2 is compatible with Era

Need to have a hard green light / red light on whether this is possible, so that we can work through implications with BD + Era teams

**Comment by codenamejason** [comment]
- [ ] V1 successful deploy and verify
- [ ] V2 successful deploy and verify

**Comment by thelostone-mc** [comment]
Looks like the spike is complete. Next we'll get the code merge ready when we have the actual deploy
