### ISSUE TITLE
[spike] Fund pool from Anchor

### ISSUE THREAD

**Issue by 0xZakk** [allo-protocol/allo-v2#251]
One use case I'd like to make sure is possible:

Could a DAO fund the anchor address of a profile for a grant-giving body, which can then fund pools from the anchor address. (Let me know if this doesn't make sense) Theoretically, this should be possible, but I think we want to verify:

- proposal passes in Governor Bravo and Eth, USDC or some other token is transferred to an anchor address
- profile owner or member calls `createPool` and funds it with some portion of that balance

**Example use case:**

Prezenti is a grant org in the Celo ecosystem. They request $1,000,000 USDC to distribute in small grants. The proposal passes and is executed by Celo's governance contracts (the $1,000,000 USDC is transferred to Prezenti's anchor address). Members of Prezenti can then create a pool for running a direct grants program and fund it with $200,000. Members of Prezenti can create a separate pool to run a QF round and fund it with $25,000.

**I want to verify that:**

- funds in the anchor can be easily used to fund a pool
- this can be done without having to transfer funds out of the anchor first (i.e. transfer funds from the anchor, to a multi-sig or wallet, then to fund the pool)

**Why is this important:**

- The profile is meant to be the onchain representation for every project (recipient and/or donor of funds)
- The audit-ability of how funds flow through Allo is really important for end users/communities

**Comment by 0xKurt** [comment]
The `anchor` can receive funds and call `fundPool`

But, currently **only** a profile owner is able to execute functions on the anchor.
If needed, one could set a MultiSig or another contract as a profile owner to execute the anchor.

Also the pools can be funded by anyone, that means even a governor would be able to call `fundPool`
If needed, an anchor could create a pool, but the anchor needs to be added to the profile members before.

**Comment by thelostone-mc** [comment]
Yup this works ! Anchor would be able to 
- fund pool
- create pool (but would have to be added as the pool manager)
