### ISSUE TITLE
Deploy Allo v1 Contracts to Avalanche & Fuji Testnets

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#258]

**Comment by thelostone-mc** [comment]
Testnet 

- https://github.com/allo-protocol/allo-contracts/pull/93
- https://github.com/allo-protocol/graph/pull/22

**Comment by codenamejason** [comment]
Avalalnche Mainnet

- https://github.com/allo-protocol/allo-contracts/pull/93
- https://github.com/allo-protocol/graph/pull/24

**Comment by codenamejason** [comment]
Should we put the graph on another ticket (I should be able to wrap up today)? @nfrgosselin @thelostone-mc

**Comment by thelostone-mc** [comment]
We could do it next time going forward. I think it's fine to keep it one ticket cause they are simple tasks but we can try it out next time, to make tracking easier
