### ISSUE TITLE
(spike) hosting recommendation for AlloScan

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#311]
**timebox to 1 hour**

We need to figure out where we want to host AlloScan (service + URL). 

The scope of this ticket is to research options and provide a recommendation back to the team on standup. Remember that we need to ship a completed project by Aug 22, so the proposed solution must fit into that appetite. 

**Resources:**
- [Shape-up doc](https://docs.google.com/document/d/1nDEFWMTYUNx147dJaY7DCxbt031F9ofVDGtQcmXRwdw/edit)
- [Miro planning board](https://miro.com/app/board/uXjVMnFEv8s=/?share_link_id=781896803122)

**Comment by thelostone-mc** [comment]
https://github.com/allo-protocol/allo-v2/issues/310#issuecomment-1713688570
