### ISSUE TITLE
Allo Supported Networks

### ISSUE THREAD

**Issue by codenamejason** [allo-protocol/allo-v2#386]
### Networks Supported

✅ Ethereum 
✅ Optimism
✅ Arbitrum
✅ Polygon
✅ PGN
✅ zkSync Era
✅ Celo
✅ Base

Not Currently Supporting:
❌ Fantom
❌ Avalanche

### Graph Deployments

✅ Ethereum
✅ Optimism
✅ Arbitrum
✅ Polygon
✅ PGN
✅ zkSync Era
✅ Celo
✅ Base

### Spec Support

✅ Ethereum
- [ ] Optimism
- [ ] Arbitrum
- [ ] Polygon
- [ ] PGN
- [ ] zkSync Era
- [ ] Celo
- [ ] Base

**Comment by 0xKurt** [comment]
jfyi:

Safe supports the followig networks:
Ethereum, 
Gnosis, 
Polygon, 
BNB SC, 
Arbitrum, 
Aurora, 
Base, 
Polygon zkEVM, 
zkSync Era, 
Avalanche, 
Celo, 
Optimism, 
Base Goerli Testnet, 
Goerli

From the list above: PGN and Fantom are not supported

**Comment by codenamejason** [comment]
@0xZakk did you get any confirmation from Spec yet on supported networks?

**Comment by 0xZakk** [comment]
Waiting for Ben to confirm. He said they would be able to support these chains

**Comment by whittlbc** [comment]
Will have support for these in advance of your official launch:

- Ethereum (Mainnet)
- Goerli
- Optimism
 - Arbitrum
 - Polygon
 - PGN
-  Celo
- Base

Kicking the tires on zkSync Era per Zakk's personal message to me the other day about that

**Comment by thelostone-mc** [comment]
@whittlbc we might need to figure out a way where we can create a test workspace and make sure everything works as expected before we index the data on the actual table meant for public use.

**Comment by whittlbc** [comment]
@thelostone-mc For sure - We can just spin up a dev/staging environment for your alloscan project and have your live objects always get deployed there first before deploying to prod
