### ISSUE TITLE
Remove the need for strategies to be approved

### ISSUE THREAD

**Issue by 0xOneTony** [allo-protocol/allo-v2#574]
Following on Kevin’s [list](https://github.com/allo-protocol/allo-v2/issues/544) we want to 
> remove the paternalizing requirement that allo team "approves" every strategy.

Context
---
Currently there are 2 options to create a new Round.
1.  With cloneable strategy. Allo stores a mapping with addresses of Strategies that are approved by the protocol and can be safely cloned for a new Round.
2. With a custom strategy. The user provides an already deployed Strategy contract that is not part of the accepted cloneable mapping. 

Solution
---

To achieve that we should update the `Allo` contract as:
- [ ] We assume all strategies cloneable/approved
- [ ] Removal of `cloneableStrategies` mapping
- [ ] Removal of `createPoolWithCustomStrategy` function
- [ ] Removal of `addToCloneableStrategies` function 
- [ ] Removal of `removeFromCloneableStrategies` function
- [ ] Removal of `_isCloneableStrategy` & `isCloneableStrategy` functions
- [ ] Update `createPool`
- [ ] Update docs
- [ ] Update tests

Questions
---
Is this change gonna affect the SDK or any other offchain tool that we should account for?

**Comment by carlbarrdahl** [comment]
Looks great to me! 

Can we also remove this line or is that a separate issue? (#6 in @owocki 's list)
https://github.com/allo-protocol/allo-v2/blob/7a6ea4ba3eeaabb7d8070c0e9a111cee77ed51c9/contracts/core/Allo.sol#L440

Removing this line will reduce friction in creating pools for new users.
What are your thoughts @thelostone-mc ?

**Comment by 0xOneTony** [comment]
> Can we also remove this line or is that a separate issue? (#6 in @owocki 's list)

Yes, I agree, will open a different issue and PR for this
