### ISSUE TITLE
Ensure core contracts support offchain voting/ meta-transactions

### ISSUE THREAD

**Issue by thelostone-mc** [allo-protocol/allo-v2#594]

**Comment by 0xOneTony** [comment]
Can you explain a bit more the scope of the task?

**Comment by thelostone-mc** [comment]
The scope here is that we have clients who would would want to do all the allocation off-chain and use a relayer to pay fees. We'd just have to validate that the core protocol supports a relayer to pay the fees / enable a strategy can be written to support this
