### ISSUE TITLE
Enhancement ideas

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/allo-v2#6]
From @KurtMerbeth 

I would like to share my thoughts after walking through [the strategy miro](https://miro.com/app/board/uXjVMXyfa-o=/).
Maybe I can have your thoughts on it.

1. I would like to propose the addition of check functions for the functions in the core contract to enhance safety and usability:

    Examples: 
    `claim(uint _poolId, bytes memory _data) external;`
    Proposed Check Function: `isClaimable(uint _poolId);`
  
    `applyToPool(uint _poolId, bytes memory _data) external`
    Proposed Check Function: `canApply(uint _poolId, bytes memory _data)`
    
    etc..
    
    These check functions will enable frontends, users and other contracts to verify if executing the corresponding operations is possible or not, based on predefined conditions or requirements. 

2. I would like discuss the idea of introducing an `execute` function that would enable calling custom functions within Strategies through the Core contract. This feature aims to streamline pool handling and provide a unified approach for interacting with both standard and custom functions within Strategies.

    Pros:
    
    - Simplified Pool Handling: With the `execute` function, users and developers can interact with Strategies seamlessly through the Core contract, regardless of whether the functions are standard or custom. This streamlines pool handling and reduces the need to switch between different contracts, enhancing usability and developer experience.
    
    - Centralized Transaction Flow: By consolidating the function calls within the Core contract, the transaction flow becomes more centralized and easier to follow. This can improve the clarity and maintainability of the codebase.

    Cons:
    
    - Potential Security Risks: Introducing an execute function that allows arbitrary function calls to custom Strategy functions carries inherent security risks. Careful consideration must be given to access control and validation mechanisms to prevent unauthorized or malicious function executions.
    
   -  Increased Complexity: Implementing the execute function adds complexity to the Core contract and may require additional validation and error handling logic. This can increase the development and testing effort required to ensure the robustness and reliability of the system.
   
3. Currently, the Core contract has a function called `claim`, but as we introduce distribution strategies that handle fund distribution to users, the name `claim` seems in some cases a bit misleading since `claim` is usually used as an action executed by an user. 

    To address this, I suggest adding an adtional function called `distribute` to the Core contract. This function will be responsible for initiating the distribution of funds to users by the pool owner.
    
    Alternatively, we could think about introducing a new name which represents both, `claim` and `distribute`. I don't have any suggestions right now, but I was thinking about a more generic name like `handleDistribution`.

___

from @thelostone-mc 

> I would like to propose the addition of check functions for the functions in the core contract to enhance safety and usability:

I do like having these for enhancing safety check 

> Adding `execute` function.
I do see the benefit in flows like milestone based payout where :
- project owner submit milestone 
- this function would exisist on the allocation strategy and in our current interface , the project owner would be forced to interact with the allocation contract instead of round
- Having the execute solves this but this feels quite scary. we could make it safer by saying no re-enterancy and maybe not payable. 
I'm split on this 

> rename claim as handleDistribution

In favour of this 

____

from @KurtMerbeth 

> Having the execute solves this but this feels quite scary. we could make it safer by saying no re-enterancy and maybe not payable. I'm split on this

I feel the same. I wanted to encourage some thought on this matter. 
Perhaps there is a viable way to implement something like this while ensuring safety. On the other hand, it's possible that the potential risks outweigh the benefits. Do we even consider it a problem worth addressing?

The idea of having one entry point for everything came up while I was going through the diagrams.

____

from @thelostone-mc 

Would recommend having a updatePool on the interface cause we would def want to update the metadata
https://github.com/zobront/allo/blob/main/interfaces/IAllo.sol#L18

Also not relevant to the interface but we might want to add OZ multi-call to allow folks to allocate to multiple pools and stuff

____

from @codenamejason 

I think multi-call here is a great idea and good call out @thelostone-mc as well as adding the `updatePool()` to the interface. 

Do we need to return any data on an update or just emit an event?

```solidity
function updatePool(bytes memory _data) external payable returns (bytes memory);
```

**Comment by KurtMerbeth** [comment]
> Also not relevant to the interface but we might want to add OZ multi-call to allow folks to allocate to multiple pools and stuff

that's a great idea. i like it

**Comment by thelostone-mc** [comment]
Questions for today:

- How do we make application status more flexible 
- In flows like Merkle payout -> generatePayout would have to be flexible to pass custom data like merkleRoot. (It can't always be applicationId to percentage)
- In flows where there is an off-chain upload of results present, would it make sense to have setDistribution on AllocationStrategy / DistributionStrategy. By principle, it should be allocation but it feels wrong cause all generatePayout on allocation would do is return data.
- AllocationStrategies have a function called owner which is tor return the owner of pool, this would likely be a list. Would it make more sense to have an isPoolOwner on IAllo and IAllocationStrategy.owner is renamed to  IAllocationStrategy.isPoolOwner ?

**Comment by zobront** [comment]
We'll talk about all of this in the morning, but putting my very brief thoughts here so we have something to reference. Some of Aditya's latest message not included in this list because I need more context, but most are:

YES
- isClaimable()
- canApply()
- rename claim() to distribute()
- updatePool() 
- multi call (I don't think we need a generic multicall, but I think we should have versions of the functions that allow arrays so multiple calls can be made of that type)

DISCUSS
- execute() to forward along calls to strategies => I think the trade offs aren't worth it given it would only be project owner interacting with strategies and it opens up lots of potential risks, but let's discuss
- application status flexibility => I think we are best served by simple interface and allowing them to use any application status they want interanlly, but let's discuss
- In QF, should allocations be stored on Allocation and then claimed at the end of the round => i don't have an opinion here, seems best to just send them but don't really have a preference
- discuss downside bytes as argument. Would it cause issues down the line (for frontend integrations) => i don't think there's a way to do this protocol without it, you need to be able to support flexibility for strategies. can we walk through the situation where a front end would struggle with this?

FEEL PRETTY STRONGLY NO
- Would it make sense to have generatePayouts to send actual amount instead of percentage
- we have ApplicationStatus and getApplicationStatus on IAllocationStrategy, we should have a setter function

**Comment by thelostone-mc** [comment]
Ah thanks for that :D 

- Just a few more when we were looking into Direct Grants which does Milestone payout:
https://github.com/allo-protocol/strategy-library/blob/main/src/allocation/direct-grants/template.sol#L74
- Should generatePayout be payable or view function ?
