### ISSUE TITLE
Strategy Milestones Extension

### ISSUE THREAD

**Issue by 0xOneTony** [allo-protocol/allo-v2#620]
Create an extension from `CoreBaseStrategy` that will include defining and managing a strategy that uses milestone submissions and reviews. Strategies like `RFP` use milestones to allocate funds for recipients. We should offer an extension that includes all the logic of using milestones in strategies.

- Define milestone status
- Define milestone creation/submission/review
- Define roles for actors

**Comment by 0xOneTony** [comment]
@ilpepepig 
1. I see creating a milestone more like a helper function rather than being the allocation logic, we should provide this in the extension and then if the user wants this logic in `allocate` they can just call it from there.
2. Milestone submission is more like an intent, doesn't mean it will distribute, if anything reviewing a submission could be part of distribution logic.
3. I think this is answered above, we should provide a review function for milestones and just like the creation of milestones it should be up to the dev, who is building their custom strategy, how they will use them.

wdyt?

**Comment by ilpepepig** [comment]
@0xOneTony makes sense, thanks!
