### ISSUE TITLE
Add ability to reduce pool amount

### ISSUE THREAD

**Issue by thelostone-mc** [allo-protocol/allo-v2#621]
From support 
> The round is now set to 862.5K Sei for the matching pool and now (since the market jumped - yay) the amount needed is more like 750K Sei.  When I tried to downgrade the total to 750K it told me that you can only add to not subtract from the matching total once it is set. 
I am curious if there is a reason we are doing this?  I think in situations like this a round manager would require the ability to change the round amount as now (with the sei community watching as payouts occur) they will wonder why only 750K was paid out from a 862.5K pool.
LMK.  I know they will ask if i can change the round amount before final payout so just trying to get in front of this question!

Currently we only allo increasing the pool amount to ensure pool managers don't lower the matchingpool later. It looks like users want to have this functionality 
- to accomodate price volatility  
- to reduce funds if there isn't enough applications / donations

**Comment by 0xOneTony** [comment]
This is more of a spike, we should explore first if it makes sense to add this on the contract side and if it will have any implications for other strategies.

**Comment by 0xAustrian** [comment]
<p>The <code>withdraw()</code> function in <code>CoreBaseStrategy.sol</code> can be used to achieve the goal of reducing the pool amount and withdrawing tokens. However having a function to reduce the pool amount can be tricky, and some users may interpret this as a rug pull (it can reduce the promised tokens amount and also access user funds if any). There should be much care if decided to use the withdraw function on a strategy, especially depending on the custom logic of the strategy and the usage of the <code>poolAmount</code> variable.</p>
<p>Some strategies use the <code>poolAmount</code> value to make calculations, if this value is decreased in between calls it can produce problems in the process. For more information check the next table of when the withdraw function should/shouldn’t be called:</p>

  | before allocation | before distibution started | after distribution started
-- | -- | -- | --
donation-voting-merkle-distribution-direct-transfer | ✅ | ✅ | ❌
donation-voting-merkle-distribution-vault | ✅ | ❌ | ❌
qv-simple | ✅ | ✅ | ❌
rfp-simple | ✅ | ✅ | ❌
direct-grants-lite | ✅ | ✅ | ✅


<p>Worth noting that, when developing custom strategies, one must take in account the usage of the variable and it’s interaction with the code.</p>
<h3>Suggested changes:</h3>
<ul>
<li><code>withdraw()</code> does not update the <code>poolAmount</code> variable. This does not happen in the <code>distribute()</code> function either (although reducing the <code>poolAmount</code> in this function can create some problems, for example, in <code>QVSimple</code> strategy it can mess the quadratic calculation).</li>
<li>To prevent an unsafe calling <code>_beforeWithdraw</code> hook must be modified with the corresponding logic. For example: in the case of <code>donation-voting-merkle-distribution-direct-transfer</code> if the <code>distributionStarted</code> is true, the function must revert. But this is not the case for <code>direct-grants-lite</code> where the function can be called at any time.</li>
<li>The Natspec of the <code>withdraw()</code> function must be updated to warn about the usage.</li>
</ul>


cc: @thelostone-mc

**Comment by thelostone-mc** [comment]
@0xAustrian Agree with this! There are scenarios where the withdraw should not be called. Will inform product to ensure that the UI must account for these corner cases as well else funds could be stuck on the contract

**Comment by 0xOneTony** [comment]
Closing since we agreed on:
- We have UI show the token amount and not USD
- Doesn't make sense to allow folks to fundPool and then reduce poolAmount and this an easy advocation for rug pool
