### ISSUE TITLE
Make project identity able to receive funds?

### ISSUE THREAD

**Issue by 0xZakk** [allo-protocol/allo-v2#86]
I know we keep having this discussion, but wanted to open it up again (for the fourth time?)

I think we may need to make it so that identities in the project registry are able to receive and hold funds (by deploying a lightweight proxy contract that people can only interact with through the Registry, similar to how Splits works). Reason being: I think it's just too natural to distribute payments to the anchor address

https://github.com/allo-protocol/allo-v2/blob/dd1b6b137b44f780717b4228d107e384b90fa2ad/contracts/strategies/NFTVoteWinnerTakeAll.sol#L142

**Comment by thelostone-mc** [comment]
Fixed via https://github.com/allo-protocol/allo-v2/pull/125
